name: "ui_eval_harness"
version: "1.0.0"
config-version: 2

profile: "ui_eval_harness"

# paths are relative to this file, now at the repo root
model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
snapshot-paths: ["dbt/snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ui_eval_harness:
    +materialized: table
    staging:
      +materialized: view
