name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync
      - name: Lint
        run: |
          uv run ruff check .
          uv run black --check .
      - name: Tests
        run: uv run pytest -q
